# This is a basic workflow to help you get started with Actions

name: Generate PDFs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "update-structure"
      
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3.3.0
        with:
          version: v27.3.1
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Cache docker
        id: docker-cache
        uses: actions/cache@v4
        with:
          path: docker
          key: ${{ runner.os }}-docker

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Build Docker image
        run: |
          docker buildx build -t "md-to-pdf" \
              --cache-to type=gha \
              --cache-from type=gha util

      - name: Git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"

      - name: Prepare files
        run: |

          shopt -s globstar

          mkdir tmp
          cp wiki/topics/* tmp -r

      - name: Build PDFs
        run: |
          docker run -v $PWD/tmp:/var/doc md-to-pdf /var/build.sh

      - name: Cleanup dir
        run: |
          shopt -s globstar

          rm pdfs -rf
          mkdir pdfs
          mv tmp/**/*.pdf pdfs -f
          rm tmp -rf

      - name: Push PDFs
        run: |
          git add pdfs
          git commit -m "pdf generation - $(date)"
          git push


