name: Build documentation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.4.0
